version: "3.8"

services:
  tamilrockers:
    build: .
    container_name: tamilrockers
    restart: no
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TAMILROCKERSURL: ${TAMILROCKERSURL}
      #IP: ${IP}
      #TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      #TG_CHAT_ID: ${TG_CHAT_ID}
      #QBITIP: ${QBITIP}
     # QBITUSER: ${QBITUSER}
     # QBITPASS: ${QBITPASS}
     # HOMEASSISTANTWEBHOOK: ${HOMEASSISTANTWEBHOOK}






