version: "3.8"

services:
  tamilrockers:
    build: .
    container_name: tamilrockers
    restart: no
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TAMILROCKERSURL: ${TAMILROCKERSURL}
      #IP: ${IP}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      QBITIP: ${QBITIP}
      QBITUSER: ${QBITUSER}
      QBITPASS: ${QBITPASS}
      HA_WEBHOOK_URL: ${HA_WEBHOOK_URL} #triggering next app after complting current app tasks






